### ISSUE TITLE
igUpload unable to upload multiple files in same http request

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#1228]
### Description  
Describe the issue.

I want to upload multiple files within the same XHR request, and I use the sample from here, https://jp.igniteui.com/file-upload/multiple-upload, when I select multiple files, it will still send 
two xmlhttp request.
### Steps to reproduce  

1. Step 1
open https://jp.igniteui.com/file-upload/multiple-upload
2. Step 2
select two files.
3. Step 3
Upload and check Network tab in Chrome developer tools, 

### Result  
I hope there is an option to allow use the same XHRHttpRequest to upload multiple files.
just like in plain javascript, we can do like this.

```javascript
function uploadFiles(files) {
    var xhr = new XMLHttpRequest();
    var formData = new FormData();
    xhr.onload = successfullyUploaded;
    xhr.open("POST", "http://localhost:3000/upload", true);
    xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');
    for(var file in files) {
        formData.append("uploads", files[file].data);
    }
    xhr.send(formData);
}
```
### Expected result  

Add an option to allow to send multiple files in a single XHR request.

### Attachments  
here is a screenshot
<img width="1440" alt="2017-09-26 16 54 42" src="https://user-images.githubusercontent.com/1442575/30848914-9244e4d2-a2db-11e7-890f-900c57b5c251.png">

**Comment by gedinakova** [comment]
- [ ] Implement multiple files upload in a single XHR #1501
- [ ] Implement tests for multiple files upload in a single XHR #1502
- [ ] Document multiple files upload in a single XHR feature #1503
- [ ] Update "Multiple Upload" sample with the new option to upload in a single XHR #1504
