### ISSUE TITLE
Update CI build npm deploy

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#1764]
### Description  
Per https://status.npmjs.org/incidents/dn7c1fgrr7ng all deployments in branches need to be updated with new tokens. 
Will use this issue for multiple Ignite UI repos for easier tracking.

The update should be applied to the following repos/branches:

- IgniteUI/ignite-ui
  - [x] master #1767
  - [x] 18.1 #1766
  - [x] 17.2 #1765
- [x]  IgniteUI/igniteui-angularjs IgniteUI/igniteui-angularjs#124
- [x]  IgniteUI/igniteui-react IgniteUI/igniteui-react#102
- [x] IgniteUI/igniteui-angular-wrappers IgniteUI/igniteui-angular-wrappers#283
